"""empty message

Revision ID: d55618a94f23
Revises: 
Create Date: 2022-11-05 15:53:28.067044

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd55618a94f23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_id', table_name='post')
    op.drop_table('post')
    op.drop_index('ix_rubrick_id', table_name='rubrick')
    op.drop_table('rubrick')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rubrick',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bound_post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bound_post_id'], ['post.id'], name='rubrick_bound_post_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='rubrick_pkey')
    )
    op.create_index('ix_rubrick_id', 'rubrick', ['id'], unique=False)
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='post_pkey')
    )
    op.create_index('ix_post_id', 'post', ['id'], unique=False)
    # ### end Alembic commands ###
